### ISSUE TITLE
[Beta 8] Build error

### ISSUE THREAD

**Issue by robwalkerco** [Adyen/adyen-react-native#140]
**Describe the bug**
After updating to `"@adyen/react-native": "1.0.0-beta.8"` I'm getting an Android build error

```
e: <removed>/the-app/node_modules/@adyen/react-native/android/src/main/java/com/adyenreactnativesdk/AdyenCheckout.kt: (66, 71): Overload resolution ambiguity: 
public fun CharSequence.startsWith(char: Char, ignoreCase: Boolean = ...): Boolean defined in kotlin.text
public fun CharSequence.startsWith(prefix: CharSequence, ignoreCase: Boolean = ...): Boolean defined in kotlin.text
public fun String.startsWith(prefix: String, ignoreCase: Boolean = ...): Boolean defined in kotlin.text
```

**To Reproduce**
1. Update from Beta 7 to Beta 8
2. Clean Android project
3. Run build

**Expected behavior**
No build error

**Screenshots**
NA

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
NA

**Comment by descorp** [comment]
Hey @robwalkerco 

This is a very unfortunately bug we have introduced.
The fix is [already added](https://github.com/Adyen/adyen-react-native/pull/133) and we are going to make beta-9 release with patch this week.

Fix would be to replace all instances of `adyenRectNativeRedirectScheme` -> `adyenReactNativeRedirectScheme` in your project (or rename `adyenReactNativeRedirectScheme` -> `adyenRectNativeRedirectScheme` in `BuildConfig` 😅 ), clean your project, delete 'node_modules' and try again..

**Comment by descorp** [comment]
This was fixed on [beta-9](https://github.com/Adyen/adyen-react-native/releases/tag/1.0.0-beta.9)
@robwalkerco could you verify?

**Comment by robwalkerco** [comment]
> This was fixed on [beta-9](https://github.com/Adyen/adyen-react-native/releases/tag/1.0.0-beta.9) @robwalkerco could you verify?

@descorp When I try to build the Android app using the latest beta 9, I'm still getting a build error - 
```
/<removed>/app/android/app/src/main/java/com/app/MainActivity.java:75: error: cannot find symbol
    ActionHandler.Companion.handle(intent);
                           ^
  symbol:   method handle(Intent)
  location: variable Companion of type Companion
```
The app builds fine when using Beta 7

**Comment by descorp** [comment]
Hey @robwalkerco 

Could you try ?
```java
AdyenCheckout.handleIntent(intent);
```

---

We have introduced breaking change when converted `AdyenCheckout` to **object** from **class**.
This change is documented on [README](https://github.com/Adyen/adyen-react-native#for-standalone-components).

**Comment by robwalkerco** [comment]
> Could you try ?
> 
> ```java
> AdyenCheckout.handleIntent(intent);
> ```

Thanks. That sorted it :)
