### ISSUE TITLE
skipListWhenSinglePaymentMethod not working with AdyenCheckout 

### ISSUE THREAD

**Issue by iranaahsanali** [Adyen/adyen-react-native#39]
**Describe the bug**
**skipListWhenSinglePaymentMethod** is not working with web redirect payment methods that have no interaction, with AdyenChecout, but it's working with NativeModules.AdyenInstant.

here is the code that I am trying:

```
<AdyenCheckout
      config={{
        holderNameRequired: true,
        hideCvcStoredCard: true,
        showStorePaymentField: true,
        hideCvc: false
        showPreselectedStoredPaymentMethod: false,
        skipListWhenSinglePaymentMethod: true,
        clientKey: 'XXXXXXXXXXXXXXXXXXXXXX',
        environment: 'test',
        returnUrl: 'adyencheckout://',
        shopperLocale: 'en_US',
      }}
      paymentMethods={{
        paymentMethods: [
          {
            configuration: {
              merchantId: 'XXXXXXXXXX',
              intent: 'capture',
            },
            name: 'PayPal',
            type: 'paypal',
          },
        ],
      }}
      onSubmit={didSubmitCallback}
      onProvide={didProvideCallback}
      onFail={didFailCallback}
      onComplete={didCompleteCallback}>
      <CheckoutScreen
        paymentMethods={{
          paymentMethods: [
            {
              configuration: {
                merchantId: 'XXXXXXXX',
                intent: 'capture',
              },
              name: 'PayPal',
              type: 'paypal',
            },
          ],
        }}
        isVisiblePaymentMethods={isVisiblePaymentMethods}
        setPaymentMethods={setPaymentMethods}
        onPressMethodSelect={onPressMethodSelect}
        openPaymentMethod={openPaymentMethod}
      />
    </AdyenCheckout>
```

**To Reproduce**
1. Try to open any payment method that has zero interaction i.e. Paypal,
2. It will show in the payment listing screen instead of directly opening in web-view

**Expected behavior**
The web payment method should directly open in the web browser and the flow should work.

**Screenshots**
![Simulator Screen Shot - iPhone 14 - 2022-10-03 at 16 48 20](https://user-images.githubusercontent.com/18231674/193570331-e3643372-052e-4034-9899-e6a5e61995be.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 1.0.0 [BETA.5]

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: 16.0

**Comment by descorp** [comment]
BTW, AdyenCheckout will find the requested PM in the list (if present).
So no need for providing a specific payment method manually, you can simply pass the whole '/paymentMethods' JSON response from the backend.

**Comment by ahsan-lebara** [comment]
Thanks @descorp `start('paypal');` works for me for iOS. On Sofort it's crashing, I think you haven't added this payment method in your native payment methods listing.

 ```
{
        "name": "Sofort.",
        "type": "directEbanking"
},
```

Screenshot:

![Simulator Screen Shot - iPhone 14 - 2022-10-04 at 14 44 19](https://user-images.githubusercontent.com/92851121/193788508-e659df88-4484-4457-9f38-2432bc2a1ffe.png)

**Comment by descorp** [comment]
Hey @ahsan-lebara 

This error occurs when type is not present in `paymentMethods`. 
```js
  let paymentMethod = find(paymentMethods, type)
  if (!paymentMethod) {
    throw new Error(UNKNOWN_PAYMENT_METHOD_ERROR + name);
  }
```

The `paymentMethods` you provide on a code listing above contains only `PayPal` 🤔

**Comment by iranaahsanali** [comment]
The code attached is outdated, I tried to open Sofort with the complete payment methods list, and sofort was available in paymentMethods array.

**Comment by descorp** [comment]
So if you do `open('dropin')` you can see Sofort, but if you do `open('directEbanking')` - it does not?

**Comment by iranaahsanali** [comment]
Yeah, Exactly. 

The app is crashing in the same way for this payment method. `start('bankTransfer_DE')`

**Comment by descorp** [comment]
Indeed, I was able to reproduce

**Comment by descorp** [comment]
#40 Fixed in this PR

**Comment by faizantariq2** [comment]
When will you're going to release this?

**Comment by faizantariq2** [comment]
still not working even with lower case, as i think directEbanking type is not present. So, we can not start the payment method in case of sofort?

**Comment by descorp** [comment]
Hey @faizantariq2 

There is no workaround for beta5.
The problem is that the `type` in `/paymentMethods` response is case-sensitive, but I have [introduced the bug](https://github.com/Adyen/adyen-react-native/blob/develop/src/AdyenNativeModules.js#L36) that makes entered value lowcased.

Will be fixed in beta6

**Comment by descorp** [comment]
Hey @iranaahsanali @faizantariq2 

This bug should be fixed in [1.0.0-beta6](https://github.com/Adyen/adyen-react-native/releases/tag/1.0.0-beta.6)
Could you verify?

**Comment by iranaahsanali** [comment]
This issue is fixed. Thanks @descorp
