### ISSUE TITLE
2.1.0 - Android getting "Task :adyen_react-native:compileReleaseKotlin FAILED"

### ISSUE THREAD

**Issue by simonarcher** [Adyen/adyen-react-native#485]
**Describe the bug**
At the moment I have the `@adyen/react-native` package of `2.0.1` running fine.

However, when I try and update to the latest `2.1.0` of the package I get the following error when trying to compile my Android application

```
Execution failed for task ':adyen_react-native:compileReleaseKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileReleaseJavaWithJavac' (17) and 'compileReleaseKotlin' (1.8).
```

And Im not entirely sure how to resolve this.

my `build.gradle` file looks like this

```
buildscript {
    ext {
        buildToolsVersion = '34.0.0'
        minSdkVersion = 26
        compileSdkVersion = 34
        targetSdkVersion = 34
        supportLibVersion = "27.1.1"
        googlePlayServicesVersion = "16.+"
        googlePlayServicesAuthVersion = "19.2.0"
        kotlinVersion = "1.9.22"

        ndkVersion = "26.1.10909125"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath 'com.google.gms:google-services:4.4.2'
        classpath 'com.google.firebase:perf-plugin:1.4.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.2'
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
    }
}

allprojects {
    repositories {
        maven {
            url("$rootDir/../node_modules/detox/Detox-android")
        }
        google()
        // add in-app messaging dependency
        maven { url 'https://maven.gist.build' }
    }
}

subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}

 wrapper {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}

apply plugin: "com.facebook.react.rootproject"
```

And this only seems to be happening on `2.1.0` update and `2.0.1` seems fine, and I cant seem to identify in breaking change or updates I may need to do from the release notes.

any help or guidance on this would be most appreciated! :) 

thanks!

**Comment by descorp** [comment]
Hey @simonarcher 

What version of React Native, Expo(if any), Android Studio, Java, Gradle Wrapper you are using?

In 2.1.0 we have [specified `jvmTarget`](https://github.com/Adyen/adyen-react-native/blob/develop/android/build.gradle#L45-L47). It was intended to fix exactly the issue you are getting 😅

**Comment by simonarcher** [comment]
@descorp thanks for the quick reply! 

So to answer your questions

- React Native `0.74.3`
- Android Studio `Android Studio Hedgehog | 2023.1.1 Patch 2`
- Java I think is `17.0.10` (not sure how to check.. but attached a screenshot)
- and my gradle wrapper properties are this
```distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-all.zip
networkTimeout=10000
validateDistributionUrl=true
```

![Screenshot 2024-07-03 at 14 03 42](https://github.com/Adyen/adyen-react-native/assets/10696147/a3b3241a-3530-40c1-868d-2e53fdf18db6)

**Comment by descorp** [comment]
hm.. tomorrow I will try to replicate your setup to see if I can reproduce this issue.
In a meanwhile, could you try removing following lines from `../node_modules/@adyen/react-native/android/build.gradle`:

```gradle
    kotlinOptions {
        jvmTarget = "1.8"
    }
```

**Comment by simonarcher** [comment]
cool will give that a try in the meantime and let you know the results... :)

**Comment by devic021** [comment]
Hey guys

I also had a same issue with latest version and had to remove that part that is added to be able to build android app.

Removed this as a temp solution and after that i can build the app again:

```
kotlinOptions {
 jvmTarget = "1.8"
}
```

**Comment by simonarcher** [comment]
> hm.. tomorrow I will try to replicate your setup to see if I can reproduce this issue. In a meanwhile, could you try removing following lines from `../node_modules/@adyen/react-native/android/build.gradle`:
> 
> ```groovy-gradle
>     kotlinOptions {
>         jvmTarget = "1.8"
>     }
> ```

Yeah can also confirm removing this has allowed me to compile the app successfully with no issues. ☺️

**Comment by descorp** [comment]
Thanks @devic021  @simonarcher 💚

We will investigate how to make this work for everyone!

**Comment by zegenerative** [comment]
I have the same issue but then with 

> 'compileDebugJavaWithJavac' task (current target is 17) and 'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.

Expo SDK 50

[removing the kotlinOptions worked](https://github.com/Adyen/adyen-react-native/issues/485#issuecomment-2206129212)

**Comment by descorp** [comment]
Thanks @zegenerative 

We observe this problem for RN 74+ and working on making support for both old and new versions.

**Comment by descorp** [comment]
Released [2.1.1](https://www.npmjs.com/package/@adyen/react-native).
It should resolve the issue and provide "some" backward compatibility

**Comment by devic021** [comment]
@descorp 

Thanks, i will test it right away!

**Comment by viru-rathore** [comment]
I am using following package configuration, but still getting this error.
```
    "@adyen/react-native": "2.1.1",
    "react": "18.2.0",
    "react-native": "0.72.6",
```


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':adyen_react-native:compileDebugKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (1.8) and 'compileDebugKotlin' (17).

  Consider using JVM Toolchain: https://kotl.in/gradle/jvm/toolchain
  Learn more about JVM-target validation: https://kotl.in/gradle/jvm/target-validation

**Comment by descorp** [comment]
Hey @viru-rathore 

This is the opposite error :)

If we keep `jvmTarget = "1.8"`:
```
Inconsistent JVM-target compatibility detected for tasks 'compileReleaseJavaWithJavac' (17) and 'compileReleaseKotlin' (1.8).
```

If we remove it:

```
Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (1.8) and 'compileDebugKotlin' (17).
```

Could you check if 2.1.0 will work for you?

---

> Consider using JVM Toolchain

Unfortunately, to use Gradle toolchain support, one must use the Android Gradle plugin (AGP) version 8.1.0-alpha09 or higher. As you might know default gradle version for RN is 7.3.1

---

Could you list your:

- gradle version
- android gradle plugin version
- Java version
- Android studio version

**Comment by descorp** [comment]
FYI I can confirm that our latest "Adyen Android SDK" only works on React-Native 0.73+ due to android target limitation.

To make this work for RN 0.72 and below, one needs to:

- update Android `compileTarget` to  34
- set android plugin version to at least 8.1+
- use version 2.1.0

**Comment by viru-rathore** [comment]
> FYI I can confirm that our latest "Adyen Android SDK" only works on React-Native 0.73+ due to android target limitation.
> 
> To make this work for RN 0.72 and below, one needs to:
> 
> * update Android `compileTarget` to  34
> * set android plugin version to at least 8.1+
> * use version 2.1.0

This worked for me with given combination.

**Comment by simonarcher** [comment]
I can also confirm after updating to `2.1.1` I never got the problem with compiling again. :) 

so seems to be all good my side! 🙏 thank you!

(will mark this as closed :) )

**Comment by descorp** [comment]
Version 2.2.0 has been released.
Hopefully, it resolves duality and serves both old and 73+ React-Native versions - it was tested on Java 17 Zulu (recommended by [React Native](https://reactnative.dev/docs/set-up-your-environment)), but might have issues with older Java versions.
